### ISSUE TITLE
Clase pública: "Historia de la computación en Argentina: una perspectiva política"

### ISSUE THREAD

**Issue by gobstones-admin** [asamblea-cpi-unq/asamblea-cpi-unq.github.io#2]
El miércoles 11 de mayo a las 14hs en las calles San Martín y 9 de julio de Bernal (frente a la Estación de Trenes y el Banco Nación) el Dr. Pablo E. -Fidel- Martínez López dictará una clase pública en el marco de las jornadas de defensa de la Universidad Pública, gratuita, de calidad, inclusiva y pertinente.
La temática será la historia de la computación en la Argentina desde una perspectiva política, y no requiere ningún conocimiento previo, por lo cual se puede invitar a todo el mundo.

**Comment by matiasmelendi** [comment]
@gobstones-admin si tenes algo más extenso para poner, podemos agregarlo (algo así como la versión larga del post). Este blog te permite poner una versión reducida y además te da la opción "Seguir leyendo" para mostrar un contenido más largo. Es una opción, también podemos ponerle alguna imagen, si no tenes una puedo usar alguna de las clases públicas que ya se dieron. Te parece?
